### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by nynhex** [ozra/onyx-lang#100]
Been a while since any issues have been touched or commits made.  I'm not a crystal expert but I'd be happy to help.  I really like the idea of Onyx.

**Comment by ozra** [comment]
I'm glad to here we are more people liking it - than me :)

I've been dead-deep-invested with my time lately. Overly optimistic time planning has lead to more months of horse-tough working than I'd expected.

Onyx is _definitely_ here to stay.

What has happened during the publically non-eventful time "invisibly" is:
- about 20+ A4-papers more of ideas and to-self-discussions regarding design choices, changes and additions
- kept the source base up to date with Crystal upstream, when I've mustered pulling some time away from duties. Still some WiP changes on macro-parsing keeps me from pushing...
- been using it myself for minor "one-off" programs and such to keep gathering experience in how it feels and works out in practise.

Help is always appreciated and makes for a better project than a narrow-minded megalomanic one-man dream :-)

While the project is still in hiatus you could always _comment on RFC issues and provide your feedback and perspective._

Feedback and criticism helps a-lot to up the game and gradually removing gotchas and design flaws while adding coherent features.

Spill you mind out!
