### ISSUE TITLE
[Question] Does this language has reader macros implemented and supports template programming?

### ISSUE THREAD

**Issue by phantomcraft** [ozra/onyx-lang#106]
In the README is said: "Template-macros and AST-macros".

Does this language has support for reader macros like Common Lisp has?

In the [page about Template metaprogramming](https://en.wikipedia.org/wiki/Template_metaprogramming) in Wikipedia has this citation:

`Templates are different from [macros](https://en.wikipedia.org/wiki/Macro_(computer_science)#Programming_macros). A macro is a piece of code that executes at compile time and either performs textual manipulation of code to-be compiled (e.g. [C++](https://en.wikipedia.org/wiki/C%2B%2B) macros) or manipulates the [abstract syntax tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree) being produced by the compiler (e.g. [Rust](https://en.wikipedia.org/wiki/Rust_(programming_language)) or [Lisp](https://en.wikipedia.org/wiki/Lisp_(programming_language)) macros). Textual macros are notably more independent of the syntax of the language being manipulated, as they merely change the in-memory text of the source code right before compilation.`

Does Template-macros in the README mean Template programming?

**Comment by Sod-Almighty** [comment]
PSA: This language is dead. It has been dead for years. Move along.

**Comment by phantomcraft** [comment]
Ok, right.
