### ISSUE TITLE
Feature request: unnecessary whitespace lowers operator precedence

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#36]
This would tidy up certain expressions that currently involve ugly parentheses.
```
puts 2 * 4+1			-- equivalent to 2 * (4 + 1)
puts 2*4 + 1			-- equivalent to (2 * 4) +1
puts 2 * 4.increment	-- equivalent to 2 * (4.increment)
puts 2 * 4 .increment	-- equivalent to (2 * 4).increment
```

**Comment by ozra** [comment]
This is out of the question. Nim has a specific mode for this, if you'd like to try it.

- My rant about the delicacy of significant space whens and when nots, and why, in https://github.com/ozra/onyx-lang/issues/30#issuecomment-188797259 explains why I think so.
- I also think those look uglier _than_ the parenthesized expressions.
- On top of that it only works for "one level", (unless you start counting spaces [Nim does that], and, wooo, seriously - no!)

**Comment by ozra** [comment]
I'll leave it open, should some strangely fresh idea emerge from the clashing views.

**Comment by stugol** [comment]
Fair enough. It wasn't particularly important.

**Comment by ozra** [comment]
Closing time.
