### ISSUE TITLE
How usable is Onyx currently?

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#37]
I realise the language is still in flux, and subject to change. But how usable is it currently? Can I write a program in Onyx instead of Crystal and expect it to work?

(Also, does Onyx suffer from the ridiculous signed/unsigned int problem I recently reported on the Crystal forums; and which has apparently remained unfixed for TEN MONTHS?)

**Comment by ozra** [comment]
You're right, Onyx is much fresh, much alpha [sic].

There are no doubt bugs lurking when it comes to syntax, but I wouldn't think anything that wouldn't be possible to work around while waiting for a fix (reporting bugs makes us happy!)

There is one important aspect to remember and that is that onyx and crystal nodes - together - marry into the final program. This means, any deep core bugs in Crystal _will_ reveal them selves in Onyx too.

Now, it is of course in my interest to fix those bugs too, so there's one more active developer now. Still, I have a lot of issues to put the time on.

The major part missing at the moment is defining macros! Syntax and expression block handling in them must be settled, I'll open an issue about that.

**Comment by stugol** [comment]
I want to use it too.

How do I get it? And compile it? The exact same way I would with Crystal? Install the Crystal dependancies (like GC) and call `make`?

**Comment by ozra** [comment]
The info is in the README.md.
If you already have deps according to Crystal:
- clone the onyx repo
- run `make bootstrap`

and it takes care of itself... (fingers crossed ;-) )
