### ISSUE TITLE
Possibility of requiring named arg in func def

### ISSUE THREAD

**Issue by ozra** [ozra/onyx-lang#39]
Good syntax proposition: https://github.com/ozra/onyx-lang/issues/16#issuecomment-186940340

**Comment by ozra** [comment]
Named arguments has been considerably improved, but will not be required. Now follow similar rules to Python.

**Comment by Sod-Almighty** [comment]
Making named arguments mandatory is a Very Good Idea™. Why are we dropping this?

**Comment by ozra** [comment]
Motivation?

**Comment by Sod-Almighty** [comment]
Same motivation as mandatory unnamed arguments - the necessity of which surely you accept? - except with the advantage of explicit naming. It's a common idiom in Obj-C and Swift, and even Ruby supports this now.

Indeed, an argument could be made for the abolition of _unnamed_ arguments completely. They lead to sloppy code.

**Comment by ozra** [comment]
I would say that any function that requires named parameters to keep track of what their purpose is, is a badly designed function ;-)
Now, naturally these bad boys of functions are an unfortunate practical necessity, much of the time, in the imperative world. But I still see no reason to _force_ a user to pass arguments via keyword names. Good programming practices should be promoted, but not forced.

I'd like to strive towards:
Less things forced on the user.
More constructs available for _self chosen enforcement_.

I'm considering the essence of your want, thinking out of above mentioned perspective. With the "code modes" concept (being able to demand different levels of strictness on code in different lexical scopes) - it could simply be added as a hardening-mode: `'!require-named-argument-calls` - or something similarly named.

**Comment by Sod-Almighty** [comment]
Provided there is a mechanism whereby this can be mandated, that's fine.

**Comment by ozra** [comment]
I'll take the liberty to expand further on this track.
The suggested method, in tandem with "suggestion-decorations" in the function def params is also an alternative. 

Like the existing idea of:
```onyx
type Foo
   foo() -> 'please-dont-override-me
      do-shit()
```
Like "final", but, once again, just a recommendation. The use can then with directives choose to "require `redef` modifier for all overridden", or "for all overrides where the original is marked with the 'dont-override'", or "no explicitness required at all - just override at the drop of a hat" (that is: no demand directives are used).

Note: "please-dont-override-me" is naturally not what that pragma _will_ be called ;-)

So for this case, something like:
```onyx
my-fun(my-first, my-second!, my-third! = 47) ->   -- here "name + `!`" means "suggested mandatory"
   do-stuff
```

Another option is, provided the mentioned "first-arg is anonymous, rest is not"-convention is common enough, to have a specific directive for that, without having to decorate "recommendations" for all args except the first on all funcs. That might be too stiff a rule to work in practise though?

**Comment by Sod-Almighty** [comment]
No, mandating _all_ functions to follow this rule is a bit too restrictive. But allowing the functions to specify their own rules is fine.

`!` suffix implies "mandatory parameter", not necessarily "mandatory keyword parameter". Perhaps `my-fun(arg1, "arg2", "arg3" = 47)`?

**Comment by ozra** [comment]
`:` suffix? Come again?

If it helps, here is the current function def syntax - shown with the new return-type syntax such as I'm currently re-coding it though. Would've been done today if it wasn't for the track and fields action in the forest:

`func-name(optional-ext-par-name => internal-name OptionalType = optional-value) -> OptionalReturnType`. For example:
```onyx
foo(from => from-date Date, to => to-date Date) -> Span
   do-some-shit-and-produce-a-span(from-date, to-date)

my-span = foo from: some-date, to: some-other-date
```

**Comment by Sod-Almighty** [comment]
Ruby uses the `:` suffix for keyword params:
```
def my_fn(arg1:, arg2:)
end

my_fn arg1: 10, arg2: 20
```

**Comment by ozra** [comment]
Aha, no that's not needed. You can keyword any arg you want.

**Comment by ozra** [comment]
You don't need to specify an external name, if that wasn't clear. This is all ok too:
```onyx
foo(x, y) -> say "{x} to {y}"
foo y: "code", x: "love"  --> "love to code"
```
