### ISSUE TITLE
`Type.func-name`, or `TheActualTypeName.func-name` for type scoped functions?

### ISSUE THREAD

**Issue by ozra** [ozra/onyx-lang#42]
Atm. type level- / type scoped functions are defined by prefixing name with `Type.` or `Self.`.

```
type Foo
   Type.the-func(x) -> do-stuff
end
```

Proposed alternative (see https://github.com/ozra/onyx-lang/issues/18#issuecomment-186950156):
```
type Foo
   Foo.the-func(x) -> do-stuff
end
```

**Comment by ozra** [comment]
Note, my motivation for the `Type` "keyword" style is that it stays with the "predictable spatiality" perspective. It's simply easier to spot a type level function if it's always prefixed with `Type` or `Self` instead of `Foo` or `TheMagicTypeWithAWayTooLongName`.

**Comment by stugol** [comment]
What about `@@the-func(x)`?

**Comment by ozra** [comment]
`@@` hints towards variable - which should be distinct from functions.
The `:` just looks strange to me :-/

**Comment by ozra** [comment]
This has been settled for some time to `Type` and `Self`. And likely, later on only `Self` will be kept.
