### ISSUE TITLE
Feature request: auto coercion of some kind

### ISSUE THREAD

**Issue by ozra** [ozra/onyx-lang#55]
This, came out of #27 by @stugol, I take the liberty to re-formulate the needs here:

```
do-something(value String) ->

a = ["fred", 3, true]
do-something a.0           -- compile error
```

The wish for the above is to be able to make the compiler choose `do-something(String)` _and_ of course coerce the argument to `String` (in this particular case).

**Comment by stugol** [comment]
If multiple matches are equally applicable, should throw a 'not most specific' compile error, a la C.

The only thing really to nail down is the syntax. Prefix with * or & maybe?

**Comment by stugol** [comment]
Or a unary ^

**Comment by ozra** [comment]
For a while I've been tinkering with `'Type` (automatic qualification), `~Type` (mutable), `^Type` (immutable). It's actually implemented and flags AST, but don't act upon it yet.

That was a side note.

`~` has the connotation of "fuzzyness", "almost same", so a candidate.

(PS - don't know how to PM on github [not possible?], but you may be interested in https://github.com/ozra/atom-onyx DS)

**Comment by ozra** [comment]
In any event, choice of syntax is the easy part. How should the mechanism work? What matching, prioritization rules and demands etc.

**Comment by stugol** [comment]
I figured the syntax would be used at the point of call:
```
fn(a : String) ->
value = ["woo", 1][0]
fn ^value
```
Alternatively, perhaps we should do it [like VB.NET does](https://support.microsoft.com/en-us/kb/311329):
```
Option Strict On

fn(a : String) ->
fn ["woo", 1][0]
```

Anyhow, the way it would work is fairly straightforward. If it is plausible that the value _could_ be of the required type (or a more general type), then it is valid. At runtime, if it turns out that the type does not match, an exception would be raised:
```
fn(a : String) ->
fn ["woo", 1][1]        -- TypeException at runtime
```

**Comment by stugol** [comment]
> you may be interested in https://github.com/ozra/atom-onyx DS)

Sure, I'll check it out.

What does "DS" mean?

**Comment by ozra** [comment]
What if there are `fn(Str)`, `fn(Int)` etc. - several that match, but not enough to match all cases of the passed arg?

> What does "DS" mean?

Deinde Scriptum, I just have a habit of ending Post Scriptums with it, whether I've actually have signed before it or not.

**Comment by stugol** [comment]
If there is more than one possible match, throw a compile error:
```
fn(a String) ->
fn(n Int) ->
values = ["woo", 3, false]
fn values[0]                             -- compile-time error

fn2(n Int) ->
fn values[0]                             -- runtime error

fn values[1]                             -- no error
```

**Comment by ozra** [comment]
Note, at compile time there is two matches for the "no error" line too (the same as the first). A solution that causes run-time errors in relation to types is not desirable; that defeats the purpose of the help a type system provides. Might as well sling around javascript at that point.

**Comment by stugol** [comment]
Sorry, I meant `fn2` in the last two lines.

**Comment by ozra** [comment]
Of course, thinking about it, this is as simple as:
```onyx
values = ["woo", 3, false]

fn2(n Int) -> say "{n}"
fn2(x) -> raise "I wan't prepared for that type!"

fn2 values.1
fn2 values.0
```

Problem solved.

**Comment by ozra** [comment]
I just added throw away params to the parser, so:
```
fn2(_) -> raise "I wasn't prepared for that type!"
```
or even
```
fn2(..._) -> raise "I wasn't prepared for that type!"
```
can be used.

**Comment by stugol** [comment]
We have a type glob???

I suggest that functions taking throwaway parameters should be lower priority for matching than functions taking a value, even if no types are specified.

We should have the compiler automatically generate throwaway variants of functions if a flag is set at the top of the code. Thus, loose typing.

**Comment by stugol** [comment]
But not a splat, unless the main function takes a splat. The number of params should be the same.

**Comment by ozra** [comment]
It's just a fancy explicit way of not adding explicit type restriction.

There are rules for selecting most appropriate matching function, and they're based on param counts and their types. If you declare the same combo twice, the latter will override the previous. No matter how you name the parameters. There's no reason to change that. Simply don't define conflicting methods. When overriding 3rd party lib, your takes precedence - your choice.

Loose typing is bad. Period. If you wanna use bad programming practices, that's cool, just define like in the example:
```onyx
new-fancy-func(_, _, _) -> raise "Unintended"
new-fancy-func(a Str, b Int, c Int) ->
   do-stuff
```
It's not that much code - and it's still _not recommended_.
I can't think of one single algorithm ever where this would be better than writing it proper,
Real world example?

**Comment by stugol** [comment]
I've already given you an example. Variadic arrays. It is currently impossible to pass an element of an array to a function without casting, if the array contains more than one type of value. Tuples don't have this problem, but cannot be extended at runtime. Loose typing would solve all of this:
```
do-thing(s String) ->

values = ["woo", 17, ...]

do-thing values[0]      -- I know this is a string, so why can't I just pass it to the function?
```
The way things currently stand, I need to explicitly cast _everything_. What I propose is simply the option for implicit casting.

**Comment by ozra** [comment]
With real world I mean: where would you have a variadic array, where you know what type individual elements are, even though they vary? I can't come to think of any reasonable scenario.

And still: would declaring a catcher function hurt so much? Then it's explicit what happens too.

**Comment by stugol** [comment]
Well, it's been 6 days, and uh....I got nuthin' ;)

**Comment by ozra** [comment]
Haha, we'll leave it open for a while if something surfaces :-)

Some kind of coercing is probably good in some context, we'll figure it out.

**Comment by ozra** [comment]
The use cases in this issue are clearly covered with the clean solution of adding a "liberally signatured  function" that raises. Closes.
