### ISSUE TITLE
Feature request: named and multiple blocks

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#56]
The language would be much more powerful if constructs like this could be done:
```
my-if(&condition, &trueblock, else: &falseblock) ->

my-if { ... }
   { ... }
else
   { ... }
```
We'd need to allow braces to delimit parameterless blocks.

It would be really useful, to allow new control structures to be written in user space. For example, Go's channel select.

**Comment by stugol** [comment]
The braces would presumably be unnecessary if correct indentation is used. Anything following the `if` on the same line is the first block.

**Comment by stugol** [comment]
Either:

 - any non-block expression where a block parameter is expected is cast to a block containing the expression; or

 - braces are mandatory in the condition; or

 - special syntax for the condition parameter in the function signature.

**Comment by ozra** [comment]
Hmm, this one will need a good thinking about. Please come up with some real world example where it would make code clearer / terser / whatever, so I can relate to it. I have a hard time picturing its' actual use.

**Comment by stugol** [comment]
I guess I was thinking of the `select` functionality [here](https://gobyexample.com/select). But upon reflection, it wouldn't be made any easier by having multiple blocks.

There are other uses for passing multiple blocks into a function, though:
```
def read(&block, &error-block)
   loop {
      value = get-value
      if value > 0
         yield v
      else
         error-block.(v)
   }
end

read-values { |v|
   do_something_with v
} error { |v|
   puts "#{v} is not a valid value"
}
```

**Comment by ozra** [comment]
Just a small note, if it is decided it's a good idea, the syntax would likely be like this, to stay with current Onyx-constructs:
```onyx
read-values (v) ~>
   do_something_with v
, #error = (v) ~>
   say "{v} is not a valid value"
```
Or with the proposed slant-version (which I know you didn't like, and I have my reservations too, but just for kicks:)
```onyx
read-values (v)\
   do_something_with v
, #error = (v)\
   say "{v} is not a valid value"
```

But then again, there's nothing stopping one from adding "named blocks" (which would really just be a way of naming them according to param name, instead of using regular named args `#param = val` [once again with the "disliked" syntax just to air it a bit]), something like:

```onyx
read-values (v)\
   do_something_with v
, error(v)\
   say "{v} is not a valid value"
```

or, again, with the current block syn, but named style:
```onyx
read-values (v) ~>
   do_something_with v
, error(v) ~>
   say "{v} is not a valid value"
```

**Comment by stugol** [comment]
I meant I would like a special syntax for doing this.

Also, I'd like braces (placed after any parens) to **remain** a syntax option, a la Ruby/Crystal:
```
fn(4) { code }
-- same as
fn(4, ~> code)
```
I _strongly_ dislike the idea of having to place lambdas inside parens:
```
fn(4, ~>
   code
   code
   code
)     -- ew! :(
```
The `~>` syntax is fine for most circumstances; but there are times when parens are required; and in those cases, I want the braces option.

**Comment by stugol** [comment]
Besides, Ruby and Crystal have the notion that a `Proc` is disjoint from a block. So in Crystal:
```
fn(code1, code2)
fn ->{ code }, ->{ code }
```
This would pass two `Proc`s to the function, not two blocks; and these `Proc`s would be treated differently to blocks. **They would not be inlined.**

So in Onyx, if `~>` is a block, what's the syntax for a `Proc`? The same as Crystal? I guess that would make it less syntactically difficult to pass more than one block to a function. But still, I'd like a special syntax. Perhaps omit the comma and the equals?
```
read-values (v) ~>
   do_something_with v
#error (v) ~>
   say "{v} is not a valid value"
```

**Comment by ozra** [comment]
> I strongly dislike the idea of having to place lambdas inside parens:

Why would braces be better for grouping code than parens? Aesthetic habit?

> So in Onyx, if ~> is a block, what's the syntax for a Proc? The same as Crystal?

You guessed the syntax right. In Onyx-lingua we simply call Proc a Lambda. Since comma is a "stronger separator" (professional language ;-) ) they can be used as function args with multiple expressions on one line without needing parens (might not be recommended for readability though): `fn () -> say "hey"; say "ho", (x) -> say "{x}"`

> Wouldn't that be difficult to parse?

Yes it is ;-) But that's the job of the compiler, the programmer should just enjoy B-)

> But still, I'd like a special syntax. Perhaps omit the comma and the equals?

How about, loaning from another current idea - just use the "handler-pattern":

```onyx
-- fuck curly-lambdas ("blocks")
read(b) ->
   loop ~>
      value = get-value
      if value > 0
         b.ok value
      else
         b.error value
end

read-values <~
  ok(v) -> do_something_with v
  error(v) -> say "{v} is not a valid value"

```

**Comment by ozra** [comment]
My main reasons for being wary of multiple curly lambdas are:

1. I think they should be used sparingly to begin with - they add a vector of complexity to code, allowing the `break`, `return` and ~`continue`~ `next`. Using other ways are often better imo.
2. It will make it _much_ harder to maintain Crystal compatibility (my spare time is limited). And I think keeping that is a good thing.

**Comment by stugol** [comment]
> Why would braces be better for grouping code than parens? Aesthetic habit?

Not precisely. When using braces, they only contain the block code. When using parens, they contain all other arguments as well:
```
fn(2, ~>
   code
   code
   code
, ~>
   code
   code
   code
, 17)          -- wtf??
```
```
fn(2, 17) {
   code
   code
   code
}, {
   code
   code
   code
}            # much clearer!
```
Obviously we can't pass multiple blocks in Ruby or Crystal, but assuming we could, the second example is far clearer.

> read-values <~
      ok(v) -> do_something_with v
      error(v) -> say "{v} is not a valid value"

Wow. That actually makes multiple blocks entirely redundant, doesn't it? The visitor pattern magically solves the multiple blocks problem.

> unless err => do_something_with v
   else => say "{v} is not a valid value"

Why does this example use `=>`, when the previous used `->`?

**Comment by stugol** [comment]
Speaking of `break` and `next`, that's a good point. What if the visitor wants to halt the caller, a la `break`? Return some kind of control value? If so, this would work a hell of a lot better with brittle tuples.

Alternatively, how about special `if` support for an `Option<T>` class?
```
fn ->
   if something
      Some<int>(5)
   else
      None

if result <- fn()     # only true if Some is returned
   say result         # prints 5
```
What would work even better with visitors, is a `Control<T>` class, and language support for it:
```
fn(visitor) ->
   loop
      result = visitor.visit
      case value <- result
         when :continue
            say value            # prints "some text"
         when :halt
            break

fn <~
   visit ->
      if something
         Control(:continue, "some text")
      else
         Control(:break)
```

**Comment by ozra** [comment]
Can be called Observer, Strategy, Visitor, etc. depending on the details of how it's used. Whichever describes intent best.

Regarding the rest above, perhaps it should go in the "brittle tuples" issue, to make it easier to follow a week from now when my memory is all blank ;-), I'll reference your comment there.

**Comment by ozra** [comment]
> Why does this example use =>, when the previous used ->?

- `foo(x) -> code` - defines a function, the arrow is a beacon for that and _also_ serves as _expressions block starter_.
- `=>`, `:`, `do`, `then` are all interchangeable _expressions block starter_ (when using indent it is implicit and they can be omitted, but when writing a one-liner this can eliminate the indent.

Reminder:
`if true => code`, `if true: code`, `if true then code` - all the same. As mentioned in #7, this might be reduced, but currently they all have their places where one or the other fits better, so why not keep them as interchangeably usable tokens, letting the user decide on style?

**Comment by ozra** [comment]
I close this in favour of #49. Re-open if you feel something was left un-addressed.
