### ISSUE TITLE
Suggestion: commas optional

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#66]
Some languages allow this:
```
fn(a,b,c) ->
   say a b c

fn 1 2 3   --- "1 2 3"
```
In other words, commas can be omitted. Is this feasible for Onyx?

Multiline arrays already do this to some extent, so it wouldn't be too big a departure from the established syntax.

**Comment by ozra** [comment]
This can only ever be possible with literal arguments like numbers, tags, lists, etc.
As soon as you pop in an identifier it will be parsed as a call.
I've tried it out in languages supporting it, but I felt it only ever added confusion: Once you decide to change a literal int in some code to a variable, or worse: a call, and forget to add the comma after, you have either a boring bug or, depending on overloads, a really confusing bug!

The only pro is shaving a comma. The cons are many.

This is one of those few definite no-go's.

**Comment by ozra** [comment]
Re-opened in light of new perspectives.

**Comment by stugol** [comment]
You think this might be doable now? What's changed?

**Comment by ozra** [comment]
Definitional clarification:

1. Can _only_ be done after a literal
2. Commas can be omitted after args, _provided 1) is fulfilled_
3. Indent-style arguments can be begun at a later point than directly after function, _provided 1) is fulfilled_
4. Neither is a _recommended_ practice _unless in an obvious DSL'ish_ context (don't mix omissions with common structured code). Ultimately it is of course the coders decision, and also here the stylizer can simply convert back and forth to keep repo-style fully comma separated for instance.

**Comment by ozra** [comment]
After trying it out a bit, it causes trouble more often than not; constants feel like literals, but aren't, and _cause type-new calls_, this will be a no go.
