### ISSUE TITLE
Enumerable.some?

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#68]
```
say [nil].any?    -- prints "false"
```
This is a bit odd. At the very least, we should have a logical counterpart to `empty?`:
```
class Enumerable
   empty? -> length == 0
   some? -> length > 0
```

**Comment by ozra** [comment]
Continually sharing the module universe with Crystal is of utmost importance.
Additional code can be added to Onyx stdlib additions, but should be done with discretion to avoid unnecessary future incompatibilities.
Stdlib additions should therefore _primarily_ be discussed and PR'ed to Crystal repo.
