### ISSUE TITLE
#onyx-lang on freenode.

### ISSUE THREAD

**Issue by ozra** [ozra/onyx-lang#71]
Since I don't feel like spending the time on https://www.onyx-lang.org this very second, I abuse issues for a little "news":

I've started a `#onyx-lang` channel on freenode IRC where less formal idea juggling can be carried out along with questions etc.

I hope I got my sw setup right locally, and will try to keep it connected and eyes open, should some lone soul feel like dropping in.

**Comment by ozra** [comment]
I'll try to update "away" status from now on also :-)

**Comment by stugol** [comment]
Yup. I think it's working, but you ain't talking ;)

**Comment by ozra** [comment]
Konversation had crashed now :-/
Added notifications and bleeps :)
