### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#72]
Any plan to implement interfaces (a la COM or various other languages)? Also known as pure virtual base classes in C++.

The need for interfaces is not entirely mitigated by modules and mixins. Sometimes you want to restrict an argument by functionality, but allow the implementation to vary. Values of type `Enumerable` contain the _code_ of the `Enumerable` mixin; but interfaces allow the implementation to be defined in the class, not the module.

**Comment by ozra** [comment]
What about a trait (which "type-partials" are called in Onyx, that you mixin) with all functions defined as abstract? Then they have to be implemented in the type.

**Comment by stugol** [comment]
Is a trait the same as a Crystal module?

How are abstract functions declared? Might I suggest `⇥`?
```
fn() ⇥
```

**Comment by ozra** [comment]
Yes currently they behave the same, but Traits _will_ also support instance-vars.

abstract: Simpler than that. `fn() -> abstract`

**Comment by stugol** [comment]
Suggest unicode `⇥` alternative:
```
trait T
   fn1() -> abstract
   fn2() ⇥
```

**Comment by ozra** [comment]
For the `abstract` case there is no need to clutter the visual space with unnecessary symbols. If there's a body, there's a body, if not, you replace it with `abstract` keyword. Doesn't get any cleaner than that imo. K.I.S.S. :-)

**Comment by ozra** [comment]
As mentioned Traits (which are Modules, except not extending themselves) are all good for this.
