### ISSUE TITLE
Language concerns

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#8]
I notice that braces are used for string interpolation:
```
value = 1
puts "{value}"
```
The omission of the Ruby/Crystal `#` prefix makes unintentional interpolation far more likely, to my mind.

What is the Onyx syntax for a block or proc?

I like how you can instantiate a class without the `new` keyword: `instance = MyClass()`.

**Comment by stugol** [comment]
We need a way to declare non-interpolated strings, like the `'` in Ruby. This doesn't solve the accidental interpolation problem, but it's useful in and of itself.

**Comment by stugol** [comment]
Some suggestions:
- Typeless variables. Essentially variants. Obviously they would incur a performance hit, but sometimes ease-of-use trumps execution speed. Use of a variant would never trigger a compilation error:
```
n = 1
puts n.some-method     # run-time error, not compilation error
```
- Splat support in block arguments.

- Heterogeneous arrays. In Crystal, tuples are heterogenous, but cannot be extended or modified at runtime. They are fixed.

- Named parameters, forcing the caller to specify the parameters by name:
```
fn(a:, b:) ->
fn a:1, b:2
fn 1, 2       # error, parameters must be named at point of call
```
- Terse hash and array access:
```
a :: [] of Int32
a:0 = 2
a:1 = 4
b :: {} of Symbol => String
b:name = "Fred"
```
- Ruby-style heredocs:
```
puts <<-END.downcase
SOME TEXT
END
```
- Null-propagating operator, as seen at https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/OptionalChaining.html. Example:
`a = myobject?.method1?.method2` if any of these things are (or return) nil, sets `a` to nil and doesn't crash. I suggest either `&.` or `.?` for this purpose, as `?` already has a meaning in Ruby/Crystal/Onyx.

- Cascade operator. Allows calling methods of an object without assigning it to a temporary, and without affecting its eventual lexical value. I know `..` already has a meaning, but in this case it would be located at the start of a line.
```
return MyObject.new      # would return an instance of MyObject, no matter the result of the other calls
   .. somefunction()
   .. someotherfunction()
```
Equivalent to:
```
a = MyObject.new
a.somefunction()
a.someotherfunction()
return a
```
- Pipe operator. Nicer syntax for calling free functions in a chain. Useful to avoid nested calls. Accepts local free functions, proc objects and blocks.
```
def fn(value)
   return value + 1
end
puts 1 |> fn |> fn |> fn    # outputs 4. Equivalent to fn(fn(fn(1))), and much nicer
```
- Pipelining operator. Like the pipe operator, but works on collections. Accepts local free functions, proc objects and blocks. Also accepts methods of the items.
```
def fn(value)
   return value + 1
end
puts [1,2,3] |>> fn |>> fn    # outputs [3,4,5]
puts [1,2,3] |>> .to_s        # calls a method on each object, outputs ["1", "2", "3"]
```
- Unnecessary whitespace lowers operator precedence. This would tidy up certain expressions that currently involve ugly parentheses.
```
class Int32; def increment; self+1; end; end
puts 2 * 4.increment    # outputs 10
puts 2 * 4 .increment   # outputs 9, note the whitespace before the dot. Equivalent to (2 * 4).increment
```

**Comment by ozra** [comment]
I'm posting some issues right now, that I've prepared and touch up.
Some of them address points on your list.
Once I complete my task of posting all the RFC/DOC issues, I'll get back to this issue.

**Comment by ozra** [comment]
@stugol - Now I've gotten up a bunch of issues.
Now as to these points: it will be _much easier_ to discuss them in their own issues. Would you mind simply creating separate issues and then closing this, and I'll jump on it :-)

**Comment by stugol** [comment]
Alright, will do.
