### ISSUE TITLE
Onyx Roadmap

### ISSUE THREAD

**Issue by ozra** [ozra/onyx-lang#81]
- Rev. 5 - 2016-09-20

### Stage 1 - Basics ###
- tooling: stylizer (#93)
   - Suitable _basic set_ of configurability of style
- syntax: Complete the user defined literal suffixes (#76)
- syntax+semantics: Anonymous types (may be slightly more complex than initially considered) (#49)
- syntax: _possibly_ "non hygienic" "literal macros" (similar to C/C++ pre-compiler)
- syntax+semantics: ensure cross language Onyx-Crystal macros + templates works as intended (much more tests needed) (#53)
- semantics: "reverse inference" of literal numbers to match lvalue or params type (when exact restriction or type declaration exist) (not issed yet)
- semantics: automatic resolution of unqualified enum-constants in args and ivar assigns (when exact restriction or type declaration exist) (#52)
- Nail naming of std-types (#45)
- Decide on names of type-reasoning constructs (#74)
- Decide on preliminary naming of stdlib de-facto methods (#74)
- DOCS! (not issued)
- More samples (#54)
- tooling: Web-based "play with onyx" and "style explorer" (related to #4)
- compiler/tooling: Seamless reliable conversion of private-style vs repo-style (not issued yet)
- syntax: Unicode alternatives to ASCII-symbols / matching groupers (requires extensive testing for best choices with best support in _most fonts, editors, platforms_ with most consistent look possible) (#69)
- syntax: Weed out decidedly unwanted redundant alternatives (for ex. case/when/switch/branch/cond, etc.) (related to #13)

### Stage 2 ###
- syntax+semantics+stdlib: Parallelism model (#79)
- _Maybe_: Fast precise GC (not issued - "secret" side project ;-) )
   - May be ditched entirely if it doesn't work out (novel untried design)
   - depends on the official parallelism model of the language runtime to be ready
- syntax+semantics: versatile match-construct with destructuring (not issued yet)
- syntax+semantics: `my-fun() -> 'please-dont-override` (closest thing to `'final` for Onyx), with `'redef`, etc. as complement for monkey patching/inheritance safe guarding (_might postpone_) (not issued yet?)
- syntax+semantics: immut/mut symbols checking (_might postpone_) (not issued yet?)
- syntax+semantics: function purity declaration and validation (_might postpone_) (not issued yet?)
- clean up and refactor code base! (not issued yet)

### Stage 3 ###
- Static compilation / ensuring a way of compiling "no-deps" binaries. (#80)
- Release Onyx 1.0 alpha (not issued yet)

### Stage 4 - Post 1.0 ###
- syntax+semantics: better optimization and verification: escape analysis (not issued yet)
- syntax+semantics: possibly "code modes" concept (not issued yet)

## Notes ##
- Tweaking syntax constructs (non-breaking) may jump in at any position at any time (handling indented follow up chained calls, etc. that's not a bug, but a featureful "expected to work".)
- Changes to current syntax, elimination of redundant alternatives etc. may jump in to any position at any time.
- Changes to priorities will be edited directly in to this OP, a link to the a comment where the last update occurred will be made to make it easy to see what comments refer to the latest revision, and which to old revisions.

**Comment by stugol** [comment]
"code modes"?

I can write most of the official documentation if you like; as my grasp of English and of logic is excellent. If you want Swedish documentation... well, good luck with that, you're on your own ;)

There's no point officially documenting things that may be subject to change - at least until there is an actual release, anyway - but as we approach stage 3 I'd be happy to take on that responsibility.

**Comment by ozra** [comment]
Done: - syntax: Terse style for ~~types and~~ modules (#77)

**Comment by ozra** [comment]
Added: - semantics: "reverse inference" of literal numbers to match target var or param-type (not issed yet)

**Comment by ozra** [comment]
Added: - project: Get onyx-compiler binary tars up for bootstrapping

**Comment by ozra** [comment]
Revised the roadmap.

**Comment by ozra** [comment]
Moved this to the more obvious location: the wiki.
