### ISSUE TITLE
`Self` and `this` vs Other Namings

### ISSUE THREAD

**Issue by ozra** [ozra/onyx-lang#88]
I've been wanting this naming a long time, but put it off while looking at the naming-scheme in different languages.
Now, I've finally come to the conclusion that it is the best naming:
- `Self` (capital initial) refers to "the current type / module"
- `this` refers to the current instance (like in "C++-like" languages)

Prior art, pros and con:
- `this` is very common in many languages for the instance
- some languages has `self` for instance, and `this` for the type - the complete reverse

The motivation in two phrases:
"Let's operate on _this_ instance"
"Let's call a function on the _Self_ of this"

Currently `Self` and `Type` can be used interchangeably to refer to current type, and `self` (lowercase) refers to current instance. So, `Type` will be dropped, and `self` renamed `this` to clarify the difference.

See also #42 

Thoughts?

**Comment by stugol** [comment]
Looks alright. But how about `this` (instance) and `This` (class)?

**Comment by ozra** [comment]
I like the clearer separation between `this` and `Self`, it also makes it easier to _talk_ about the concepts (when pair-programming for instance).

**Comment by ozra** [comment]
Because of the possible confusion stemming from other languages uses, `self` will be a reserved word giving an error hinting towards `this` and `Self`.
