### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#90]
Are you dead? There's been no movement here for two months.

**Comment by phase** [comment]
I'm assuming not since @orza [just commented](https://github.com/crystal-lang/crystal/issues/2976#issuecomment-231901526) on a Crystal issue.

**Comment by ozra** [comment]
Hey! I've just moved to a new house, and there's quite a bit of carpentry and what not to get done (we've got really short summers here in Sweden).
I expect to be more actively commiting in a few weeks, meanwhile, I'm workin' on docs and some refactorizations WIP, then and when.

I'll bump when there's action :-)

**Comment by stugol** [comment]
Fair enough. Just so long as it's not dead. That would be a shame.

**Comment by ozra** [comment]
Over my dead body!
