### ISSUE TITLE
So it's dead then?

### ISSUE THREAD

**Issue by stugol** [ozra/onyx-lang#91]
4 months with no development. It was good while it lasted.

**Comment by ozra** [comment]
No worries:.4 months with no _pushes_. The summer has taken it's toll, but I've been working sporadically on it meanwhile, unfortunately not allowing consistent working-state commits and pushes, so I've held them off for a "mega push" soon. Ok, honestly - it's probably just my bad git-habits.
There's a bunch of refactors, the rolling merge-conflicts resolving to keep up-to-date and compatible with Crystal codebase, works on doc-gen, and I decided to completely ditch the internal "type-name babeling" - it was too complex for little added value, costing unnecessary time from other things in Onyx. So I think progress will flow well this autumn. The patient man always wins.

**Comment by Sod-Almighty** [comment]
Mm. Six months without movement. This project's dead.

It was fun while it lasted, but I'm done wasting my time on a non-project.

**Comment by ozra** [comment]
Well, in any event I'm glad for the input you have given so far! Thank you! I can surely understand the annoyance of a project which collects dust for unbearable time. At least it pisses me off not being able to make time for it at present :-(

The schedule has been much more pressed then I'd ever like for more and more months: bad choices and over optimistic time budgets of must-be-done-to-not-leave-the-farm-for-a-flat projects (_that old money thing_). Once, again: there is movement; just _very_ slow and non pushed.

It _is_ however just beauty sleep — like princess Thornrose. It's not dead that is; the curse of too many things to do just has to be broken for it to re-awake.
